"""Added created_at columns to Artist and Venue

Revision ID: 23cd4f02e782
Revises: 998efe5c0d3a
Create Date: 2023-11-01 00:15:34.198381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cd4f02e782'
down_revision = '998efe5c0d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
