"""Added genres to Venue model

Revision ID: 998efe5c0d3a
Revises: 4488144be062
Create Date: 2023-10-25 15:49:09.751050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998efe5c0d3a'
down_revision = '4488144be062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
